//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloresApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosflores
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string color { get; set; }
        public string relleno { get; set; }
        public int paqueteagranel { get; set; }
        public double longituddeltallo { get; set; }
        public double talloracimo { get; set; }
        public string comentarios { get; set; }
        public byte[] picture { get; set; }
    }
}
